---
application:
  name: "botminserver"
  project: "BotmindExercice"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "db"
  version: "4.4"
routers:
- name: "main-botminserver"
  routes:
  - application_name: "botminserver"
    paths:
    - "/*"
